/*
 * The MIT License
 *
 * Copyright 2014 Declan Thompson.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package proofassistant;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import javax.swing.AbstractAction;
import javax.swing.JDialog;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author Declan Thompson
 */
public class FriendlyLineInput extends javax.swing.JPanel implements ActionListener {

    JDialog parent;
    /**
     * Creates new form FriendlyInput
     */
    public FriendlyLineInput() {
        initComponents();
        myInit();
    }
    
    public void setParent(JDialog parent) {
        this.parent=parent;
    }
    
    private void myInit() {
        lineField.addCaretListener(new BracketMatcher());
        lineField.addAncestorListener(new RequestFocusListener());
        lineField.getInputMap().put(KeyStroke.getKeyStroke('V', InputEvent.ALT_MASK), "dis");
        lineField.getActionMap().put("dis", new SymbolAction(lineField, "dis"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('.', InputEvent.ALT_MASK), "imp");
        lineField.getActionMap().put("imp", new SymbolAction(lineField, "imp"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('3', InputEvent.ALT_MASK), "equ");
        lineField.getActionMap().put("equ", new SymbolAction(lineField, "equ"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('A', InputEvent.ALT_MASK), "qa");
        lineField.getActionMap().put("qa", new SymbolAction(lineField, "qa"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('E', InputEvent.ALT_MASK), "qe");
        lineField.getActionMap().put("qe", new SymbolAction(lineField, "qe"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('8', InputEvent.ALT_MASK), "time");
        lineField.getActionMap().put("time", new SymbolAction(lineField, "time"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('1', InputEvent.ALT_MASK), "noteq");
        lineField.getActionMap().put("noteq", new SymbolAction(lineField, "noteq"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('\\', InputEvent.ALT_MASK), "self");
        lineField.getActionMap().put("self", new SymbolAction(lineField, "self"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('7', InputEvent.ALT_MASK), "con");
        lineField.getActionMap().put("con", new SymbolAction(lineField, "con"));
        lineField.getInputMap().put(KeyStroke.getKeyStroke('-', InputEvent.ALT_MASK), "neg");
        lineField.getActionMap().put("neg", new SymbolAction(lineField, "neg"));
        
    }
    
    public String getLine() {
        Globals.newProofBoxPrems = lineField.getText();
        return lineField.getText();
    }
    
    public boolean usingTex() {
        return useTeXCheckBox.isSelected();
    }
    
    class SymbolAction extends AbstractAction {
        private JTextField field;
        private String symbol;
        public SymbolAction(JTextField field, String symbol) {
            this.field = field;
            this.symbol = Globals.operators.get(symbol);
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            String tempText = field.getText();
            int selectStart = field.getSelectionStart();
            int selectEnd = field.getSelectionEnd();
            tempText = tempText.substring(0, selectStart) + symbol + tempText.substring(selectEnd);
            field.setText(tempText);
            field.setCaretPosition(selectStart + 1);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        symbolSelectorPanel1 = new proofassistant.SymbolSelectorPanel();
        lineField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        useTeXCheckBox = new javax.swing.JCheckBox();

        lineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Input your line.");

        jLabel2.setText("Use brackets, and ensure they match.");

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Style Guide:");

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("(p∨q), ∀x(fx=(gx+x)), ~p, ~(~p), ∀x∀y(Rxy)");

        useTeXCheckBox.setText("Use TeX command input");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(lineField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(useTeXCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(symbolSelectorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(symbolSelectorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(useTeXCheckBox))))
        );

        symbolSelectorPanel1.addActionListener(this);
    }// </editor-fold>//GEN-END:initComponents

    private void lineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FriendlyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FriendlyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FriendlyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FriendlyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FriendlyInput dialog = new FriendlyInput(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lineField;
    private proofassistant.SymbolSelectorPanel symbolSelectorPanel1;
    private javax.swing.JCheckBox useTeXCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource().equals(symbolSelectorPanel1)) {
//            System.out.println(ae.getActionCommand());
            if (parent.getFocusOwner().getClass().equals(lineField.getClass())) {
                JTextField temp = (JTextField)parent.getFocusOwner();
                String tempText = temp.getText();
                int selectStart = temp.getSelectionStart();
                int selectEnd = temp.getSelectionEnd();
                tempText = tempText.substring(0, selectStart) + ae.getActionCommand() + tempText.substring(selectEnd);
                temp.setText(tempText);
                temp.setCaretPosition(selectStart + 1);
            }
        }
    }
}
